#!/usr/bin/tcsh -f

# Static timing analysis script using vesta -- consumes "nopower" file which is generated by synthesis but modified
# later by placement.

${bindir}/vesta --period 1E5 ${rootname}.rtlnopwr.v ${libertypath} |& tee -a ${synthlog}
